server:
  port: 8084
spring:
  application:
    name: pay-service # 服务名称
  cloud:
    nacos:
      server-addr: 192.168.195.1:8848 # nacos地址
  datasource:
    url: jdbc:mysql://localhost:3306/hm-pay?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  rabbitmq:
    host: 192.168.88.135
    port: 5672
    virtual-host: /
    username: itheima
    password: 123321
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto