server:
  port: 8082
spring:
  redis:
    host: 192.168.88.101
    port: 6379
    password: 123321
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100
  application:
    name: item-service # 服务名称
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true
    nacos:
      server-addr: 192.168.195.1:8848 # nacos地址
  datasource:
    url: jdbc:mysql://localhost:3306/hm-item?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto