server:
  port: 8090
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 192.168.195.1:8848 # nacos地址
    gateway:
      routes:
        - id: item # 路由规则id，自定义，唯一
          uri: lb://item-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/items/**,/search/** # 这里是以请求路径作为判断规则
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/users/**,/addresses/**
        - id: cart
          uri: lb://cart-service
          predicates:
            - Path=/carts/**
        - id: order
          uri: lb://order-service
          predicates:
            - Path=/orders/**
            - After=2024-07-06T20:20:20.189-07:00[America/Denver]
        - id: pay
          uri: lb://pay-service
          predicates:
            - Path=/pay-orders/**
        - id: ws
          uri: lb://websocket
          predicates:
              - Path=/ws/**
hm:
  jwt:
    location: classpath:hmall.jks # 秘钥地址
    alias: hmall # 秘钥别名
    password: hmall123 # 秘钥文件密码
    tokenTTL: 30m # 登录有效期
  auth:
    excludePaths: # 无需登录校验的路径
      - /search/**
      - /users/login
      - /users/code
      - /users/codeLogin
      - /items/**