server:
  port: 8085
spring:
  application:
    name: cart-service # 服务名称
    nacos:
      server-addr: 192.168.195.1:8848 # nacos地址
  datasource:
    url: jdbc:mysql://localhost:3306/hm-cart?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
#  cloud:
#    nacos:
#      server-addr: localhost:8848
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto